/**
 * 供其它模块使用的系统常量
 */
export class UIConstants {
  static readonly COLOR_WHITE = '#ffffff'
  static readonly COLOR_BLACK = '#000000'
  static readonly COLOR_ORANGE = '#e89e42'

  static readonly STATUS_BAR_HEIGHT = 38.76923076923077 //顶部状态栏高度
  static readonly NAVIGATION_BAR_HEIGHT = 28  //底部导航栏高度

  //水平间距
  static readonly SPACE_ROW_XS = 3    //Extra Small
  static readonly SPACE_ROW_SM = 6    //Small
  static readonly SPACE_ROW_MD = 10   //Medium
  static readonly SPACE_ROW_LG = 15   //Large
  static readonly SPACE_ROW_XL = 20   //Extra Large
  //竖直间距
  static readonly SPACE_COL_XS = 2    //Extra Small
  static readonly SPACE_COL_SM = 5    //Small
  static readonly SPACE_COL_MD = 9    //Medium
  static readonly SPACE_COL_LG = 12   //Large
  static readonly SPACE_COL_XL = 16   //Extra Large

  //字体大小
  static readonly FONT_XS = 9
  static readonly FONT_SM = 11
  static readonly FONT_MD = 13
  static readonly FONT_LG = 15
  static readonly FONT_XL = 18

  //五级灰度
  static readonly COLOR_LIGHTER = '#F0F0F0'
  static readonly COLOR_LIGHT = '#D7D7D7'
  static readonly COLOR_GRAY = '#AAAAAA'
  static readonly COLOR_DARK = '#999999'
  static readonly COLOR_DARKER = '#333333'

  static readonly COLOR_RED = '#E13C39'
  static readonly COLOR_BLUE = '#306BD2'

  //与圆角相关
  static readonly BORDER_RADIUS_SM = 3
  static readonly BORDER_RADIUS_MD = 6
  static readonly BORDER_RADIUS_LG = 10
}